fail_fast: true
repos:
- repo: local
  hooks:
  - id: python_sort_imports
    name: python_sort_imports
    entry: pipenv run sort_imports
    language: system
    types: [python]
  - id: python_format
    name: python_format
    entry: pipenv run format
    language: system
    types: [python]
  - id: python_lint
    name: python_lint
    entry: pipenv run lint
    language: system
    types: [python]
  - id: python_type_check
    name: python_type_check
    entry: pipenv run type_check
    language: system
    types: [python]
  - id: python_test
    name: python_test
    entry: pipenv run test
    language: system
    types: [python]
    verbose: true
  - id: django_test
    name: django_test
    entry: pipenv run test
    language: system
    types: [python]
    verbose: true
